import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
import re

load_dotenv()

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    api_key=os.getenv("GROQ_API_KEY"),
    temperature=0.3
)


report_prompt = ChatPromptTemplate.from_template(
    """You are a research assistant compiling a report on the topic: "{topic}"

Below are summaries from {num_sources} different sources. Synthesize them into a comprehensive,
well-structured research report in PLAIN TEXT (no Markdown), aiming for roughly 900-1400 words total.

Do NOT use any Markdown syntax anywhere — no "##" headers, no "*" or "-" bullet points, no "**bold**"
or "_italic_" markers, no numbered list syntax. Write section headers as plain capitalized text on
their own line (e.g. "Introduction", "Key Findings"), followed by a blank line, then flowing prose
paragraphs. For lists, write them as plain sentences or short lines separated by line breaks, without
any leading symbol.

The report must include these sections, in this order:

1. Introduction (4-6 sentences) framing the topic and why it matters
2. Key Findings — go in depth here. Don't just list themes briefly; develop each
   major finding into its own paragraph (4-8 sentences), explaining the reasoning, evidence, and
   any nuance behind it, not just a one-line summary
3. Differing Perspectives — even if sources broadly agree, discuss any nuance,
   disagreement, or difference in emphasis between them in real depth
4. Conclusion (3-5 sentences) synthesizing the overall picture

Do NOT include a "Sources" or "References" section at the end — the sources are displayed
separately by the application, so listing them again in the text would be redundant.

When referencing a specific finding, mention the source naturally within the sentence
(e.g., "a report from the Benton Institute found..." or "according to Yale's Budget Lab...").
Infer a reasonable, natural way to refer to each source from its URL or content — do NOT
use numbered citations, brackets, or footnote markers anywhere in the text.

Favor depth and elaboration over brevity — expand on implications, examples, and context
rather than staying surface-level.

{sources_block}

Write the full report now:"""
)
output_parser = StrOutputParser()

report_chain = report_prompt | llm | output_parser


def format_sources_block(summaries: list[dict]) -> str:
    """
    Takes a list of {url, summary} dicts and formats them into
    a labeled block for the prompt.
    """
    block_parts = []
    for i, item in enumerate(summaries, 1):
        block_parts.append(
            f"Source {i}: {item['url']}\nSummary: {item['summary']}\n"
        )
    return "\n".join(block_parts)


def generate_report(topic: str, summaries: list[dict]) -> str:
    """
    Compiles all article summaries into one structured Markdown report.
    summaries: list of {url, summary} dicts
    """
    sources_block = format_sources_block(summaries)

    report = report_chain.invoke({
        "topic": topic,
        "num_sources": len(summaries),
        "sources_block": sources_block
    })

    return report
def generate_report_stream(topic: str, summaries: list[dict]):
    """
    Same as generate_report, but yields chunks of text as they're
    generated by the LLM, instead of waiting for the whole thing.
    """
    sources_block = format_sources_block(summaries)

    for chunk in report_chain.stream({
        "topic": topic,
        "num_sources": len(summaries),
        "sources_block": sources_block
    }):
        yield chunk
def strip_markdown_symbols(text: str) -> str:
    """Removes stray Markdown syntax the model might still produce despite
    plain-text instructions, since the frontend renders content as raw text."""
    text = re.sub(r'^#{1,6}\s*', '', text, flags=re.MULTILINE)       # ## headers
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)                      # **bold**
    text = re.sub(r'(?<!\w)\*(?!\s)(.*?)(?<!\s)\*(?!\w)', r'\1', text)  # *italic*
    text = re.sub(r'^[\*\-]\s+', '', text, flags=re.MULTILINE)        # bullet points
    return text

def strip_sources_section(text: str) -> str:
    """Removes any 'Sources' or 'References' section that might appear at the end."""
    text = re.sub(r'(Sources|References).*', '', text, flags=re.IGNORECASE | re.DOTALL)
    return text.strip()
def generate_report(topic: str, summaries: list[dict]) -> str:
    sources_block = format_sources_block(summaries)
    report = report_chain.invoke({...})
    report = strip_sources_section(report)
    report = strip_markdown_symbols(report)
    return report        