# Generated by Django 5.2.16 on 2026-07-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreport',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
